
import { TermRecord, Lesson } from './types';

export const CAMEROON_ALPHABET = ['a', 'b', 'c', 'd', 'e', 'ɛ', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ŋ', 'o', 'ɔ', 'p', 'r', 's', 't', 'u', 'ʉ', 'v', 'w', 'ẅ', 'y', 'ÿ', 'z', 'ʼ', '́', '̀', '̂', '̌', '̄'];

// Les 19 Fiches Terminologiques Officielles avec images stabilisées
export const INITIAL_TERMS: TermRecord[] = [
  {
    id: '1', termeFr: 'Sensibilisation (n.f)', termeNgiem: 'lecwoŋo shwóŋ', domaineFr: 'Communication en santé', domaineNgiem: 'Leshwoŋó na nò legwɔ́ ntentʉ́',
    sousDomaineFr: 'Mobilisation communautaire', sousDomaineNgiem: 'Lecúʼte pʉ̀a shwóŋo páʼ pɔ́ ge kẅé nò Gwáʼa Mekúnɔ̀ɔn Afílikà púʼu',
    definitionFr: 'Action visant à sensibiliser les intervenants aux dangers et aux mesures préventives.',
    definitionNgiem: 'Lefaʼ meshÿó lélɔg ńcwoŋo shwóŋó paswɛ̀ mekúnɔɔn paʼ guɔ ná ngɔ́ʼ púʼu ḿbíŋ shwóŋo wɔb paʼ pɔ́ ge gÿo púʼu tá lɔg pɔ́gɔ guɔ',
    sourceFr: 'Plan stratégique PPA – IV.4.3.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) – IV.4.3.3',
    synonymesFr: 'Information sanitaire, mobilisation sociale', synonymesNgiem: 'Lecwoŋo shwóŋ pʉ̀a páʼ pɔ́ ge gÿo púʼu tá lɔg lÿɔ́ʼɔ guɔ',
    contexteFr: 'Utilisée pour prévenir la PPA par des campagnes locales', contexteNgiem: 'Mé lɔg ńtáte Gwáʼa Mekúnɔ̀ɔn Afílikà lékúu tsɛ̀ɛ láʼ.',
    idFiche: 'ISTICMEM25CAROLDFT1', imageUrl: 'https://images.unsplash.com/photo-1544225011-8f553974d612?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '2', termeFr: 'Formation des acteurs (n.f)', termeNgiem: 'Létsyeen pasẅɛ̀ mekúnɔ̀ɔn', domaineFr: 'Communication en santé', domaineNgiem: 'Leshwoŋó na nò legwɔ́ ntentʉ́',
    sousDomaineFr: 'Renforcement des capacités', sousDomaineNgiem: 'Letsyeen pʉ̀a pie pɔ́ faʼa na nò lesẅɛ mekúnɔ̀ɔn páʼ pɔ́ ge kẅiʼi zsé páʼ pɔ́ ge gÿo púʼu',
    definitionFr: "Processus d'apprentissage pour identifier et prévenir la PPA.",
    definitionNgiem: 'Ntí gie mé lɔg ńzíʼi páʼ Gwáʼa Mekúnɔ̀ɔn Afílikà áa púʼ pɔ́ lélÿɔ́ʼɔ yé',
    sourceFr: 'Plan stratégique PPA – Section IV.4.3.3', sourceNgiem: 'Letáŋté lélÿɔʼ ncù ńtíi PPA – Kèm IV.4.3.3',
    synonymesFr: 'Éducation sanitaire, renforcement des capacités', synonymesNgiem: 'Leziʼí zsénò na legÿo mekúnɔ̀ɔn gwɔ́ ntentʉ́',
    contexteFr: 'Cible : les vétérinaires, les éleveurs et les relais communautaires', contexteNgiem: 'Pʉ̀a pie yɔɔn nò líe wɔ́b : melɔ́gtà menɔ̀ɔn, paswɛ̀ mekúnɔɔn ńgÿo pʉ̀a pie mé túmo wɔ́b tsɛ̀ɛ meláʼ, pɔ́ ntÿɔgɔ́ nà nò guɔ.',
    idFiche: 'ISTICMEM25CAROLDFT2', imageUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '3', termeFr: 'Surveillance épidémiologique (n.f)', termeNgiem: 'Lelíe páʼ guɔ ne ńgiŋe púʼu', domaineFr: 'Surveillance sanitaire', domaineNgiem: 'Lelíe fʉ̀ʼ tsèm páʼ guɔ ne ńgáʼ púʼu',
    sousDomaineFr: 'Suivi clinique', sousDomaineNgiem: 'Lezoŋo gʉɔ lɔ́gtà',
    definitionFr: 'Observation régulière des élevages pour détecter précocement les signes de PPA.',
    definitionNgiem: 'Lelíe mekaba kúnɔ̀ɔn fʉ̀ʼ ntsèm létʉ njÿó ńgyɛ́ meliŋé Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)',
    sourceFr: 'Plan stratégique PPA – IV.4.4.4 (b, c)', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) – Kèm IV.4.4.4 (b, c)',
    synonymesFr: 'Veille sanitaire', synonymesNgiem: 'Legyɛ́ páʼ guɔ ne ńcʉ́ate púʼu',
    contexteFr: 'Mise en œuvre dans les zones de surveillance et de sécurité.', contexteNgiem: 'Mé lɔg faʼa jʉʼ gie mé lɔʼɔ ḿbíi fʉ̀ʼ pɔ́ gie á gíŋe te saʼá wó.',
    idFiche: 'ISTICMEM25CAROLDFT3', imageUrl: 'https://images.unsplash.com/photo-1507103011901-e954d6ec0988?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '4', termeFr: 'Rapportage de cas (n.m)', termeNgiem: 'Legÿo tà ngúmnɔ̀ɔn zsé.', domaineFr: 'Épidémiologie communautaire', domaineNgiem: 'Anò lezsé páʼ megùɔ mie é léen léen gÿote púʼu tsɛ̀ɛ láʼ',
    sousDomaineFr: 'Détection et notification', sousDomaineNgiem: 'Leszé fʉʼ gié guɔ áa ssé ḿbiŋ shwóŋo ńgúmnɔ̀ɔn',
    definitionFr: 'Signalement d’un cas suspect ou confirmé aux autorités sanitaires',
    definitionNgiem: 'Legÿo tà ngúmnɔ̀ɔn gẺie à líe nò na legwɔ́ ntentʉ́ menɔ̀ɔn, zsé páʼ mé gyeté guɔ na tsɔ̌ kúnɔ̀ɔn kà pɔ́ páʼ guɔ gwǒon tsɔ̌ kúnɔ̀ɔn mɛ́ wɔ́ɔ.',
    sourceFr: 'Plan stratégique PPA – IV.4.3.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) – Kèm –IV.4.3.3',
    synonymesFr: 'Déclaration de cas de maladie', synonymesNgiem: 'Legÿo tà mé zsé ngie guɔ áa ssé',
    contexteFr: 'Permet une intervention rapide pour limiter la propagation', contexteNgiem: 'Kẅété le flwá (rapidement) fáɛ meshó lelɔg táte guɔ le saa gìʼ',
    idFiche: 'ISTICMEM25CAROLDFT4', imageUrl: 'https://images.unsplash.com/photo-1604848698030-c434ba0851fb?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '5', termeFr: 'Désinfection', termeNgiem: 'Lepomó ffo tsɛ̀ɛ mekab', domaineFr: 'Biosécurité', domaineNgiem: 'Meshÿó lɔg ńtáte guɔ légwoon menɔ̀ɔn',
    sousDomaineFr: 'Hygiène des élevages', sousDomaineNgiem: 'Legÿo mekaba kúnɔ̀ɔn tẅɛ',
    definitionFr: 'Nettoyage et traitement des locaux et matériels pour éliminer le virus.',
    definitionNgiem: 'Lesɔg jʉʼ ńgÿo lezẅé mevilẅîs tsɛ̀ɛ mekab mbɔɔ na shúmo fàʼ.',
    sourceFr: 'Plan stratégique PPA – IV.4.4.2', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)- Kèm IV.4.4.2',
    synonymesFr: 'Décontamination', synonymesNgiem: 'Lekẅile mmó gie á náa guɔ',
    contexteFr: 'Réalisée après les abattages pour stopper la circulation du virus.', contexteNgiem: 'Mé gÿo fʉ̀ʼ gie mé zẅéte mekúnɔ̀ɔn tà ḿmag, lélɔg ńtɔʼ páʼ mevilẅîs ge gíŋe giŋte tsɛ̀ɛ láʼ',
    idFiche: 'ISTICMEM25CAROLDFT5', imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '6', termeFr: 'Règles de biosécurité (n.f)', termeNgiem: 'Lesẅɛ̀ menɔ̀ɔn na nti gie ńgwɔ́ guɔ le wɔ́b gwoon', domaineFr: 'Santé publique vétérinaire', domaineNgiem: 'Menɔ̀ɔn legwɔ́ ntentʉ́',
    sousDomaineFr: 'Normes sanitaires', sousDomaineNgiem: 'Mefʉ̀ʼ mie mé fó mǒ tá ńzsé páʼ mé ge gÿo menɔ̀ɔn gwɔ́ ntentʉ',
    definitionFr: 'Ensemble de consignes techniques et comportementales pour prévenir la PPA',
    definitionNgiem: 'Menò mie é líe levfò mbɔɔ ntí letsẅé lélɔg ńdÿɔ́ʼɔ Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA).',
    sourceFr: 'Plan stratégique PPA – IV.4.5.4', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)- IV.4.5.4',
    synonymesFr: 'Consignes de prévention', synonymesNgiem: 'Ntÿɔgɔ́ lɔg ńdÿɔ́ʼɔ guɔ',
    contexteFr: 'Doivent être vulgarisées et appliquées dans les exploitations porcines', contexteNgiem: 'Mé gẅiin légÿo láʼ cwoŋo ńzsé, ḿbiŋ fʉʼte metÿɔgɔ́ mɔ̀ɔn tsɛ̀ɛ mekàba kúnɔ̀ɔn',
    idFiche: 'ISTICMEM25CAROLDFT6', imageUrl: 'https://images.unsplash.com/photo-1606206591513-adbf6da9229e?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '7', termeFr: 'Abattage sanitaire', termeNgiem: 'Lezẅé mekúnɔ̀ɔn té zwíʼte tsɛ̀ɛ mekab mie é gẅiin guɔ', domaineFr: 'Mesures de lutte', domaineNgiem: 'Meshÿó lɔg ńzoŋo guɔ',
    sousDomaineFr: 'Éradication', sousDomaineNgiem: 'Lepyagá guɔ',
    definitionFr: 'Élimination des porcs infectés ou suspects pour contenir la propagation de la PPA.',
    definitionNgiem: 'Lezẅéte mekúnɔ̀ɔn pie é gẅiin guɔ kà pie mé ne ńgyéte guɔ ná pɔ́b wɔ́ɔ lélɔg ńtáte Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) lésa jʉʼ',
    sourceFr: 'Plan stratégique PPA – IV.4.4.4.2', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)- Kèm IV.4.4.4.2',
    synonymesFr: 'Dépeuplement', synonymesNgiem: 'Lepyág ngẅɛ̀ mekúnɔ̀ɔn gie ne ńguɔ',
    contexteFr: '', contexteNgiem: '',
    idFiche: 'ISTICMEM25CAROLDFT7', imageUrl: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '8', termeFr: 'Relance des élevages assainis (n.f)', termeNgiem: 'Lemaʼ mekúnɔ̀ɔn tsɛ̀ɛ mekab mie mé pyagá guɔ tsɔlɔ́.', domaineFr: 'Repeuplement', domaineNgiem: 'Legiŋé ḿmaʼ mekúnɔ̀ɔn tsɛ̀ɛ mekàb pɔ́ sẅé sẅé',
    sousDomaineFr: 'Résilience', sousDomaineNgiem: 'Lekàg tʉ̀ tsɛ̀ɛ ngɔ́ʼ',
    definitionFr: 'Réintroduction contrôlée de porcs dans les élevages après assainissement.',
    definitionNgiem: 'Legwaa gíŋe zyete lémaʼ mekúnɔ̀ɔn tsɛ̀ɛ mekab afʉ̀ʼ gie mé kẅilé shúm tepòŋ tsɔlɔ́, ńdié ngẅɛ̀ yembòŋo, ḿbiŋ ńtÿɔ́g pasẅɛ̀ mekúnɔ̀ɔn na ntí gie pɔ́ ge lɔg sẅɛɛ wɔ́b.',
    sourceFr: 'Plan stratégique PPA – IV.4.4.4 (v)', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)- Kèm IV.4.4.4 (v)',
    synonymesFr: 'Repeuplement', synonymesNgiem: 'Legiŋé ḿmaʼ mekúnɔ̀ɔn tsɛ̀ɛ mekàb pɔ́ sẅé sẅé',
    contexteFr: 'Nécessite un appui technique et financier pour éviter le repeuplement sauvage.', contexteNgiem: 'Á zɛ́te ntóon na zsénò kà na nò káb wɔ́ɔ ḿbɔ́gɔ lémaʼ mekúnɔ̀ɔn té pá ndyèen.',
    idFiche: 'ISTICMEM25CAROLDFT8', imageUrl: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '9', termeFr: 'Renforcement des capacités (n.m)', termeNgiem: 'Lekẅìʼi zsénò pasẅɛ̀ mekúnɔ̀ɔn', domaineFr: 'Politiques sanitaires', domaineNgiem: 'Nkwaŋá láʼ na nò mekúnɔ̀ɔn légwɔ́ ntentʉ́',
    sousDomaineFr: 'Formation et équipement', sousDomaineNgiem: 'Letsyèen pʉ̀a, ńgÿo shúmó fàʼ',
    definitionFr: 'Ensemble des démarches destinées à améliorer les compétences, les équipements et les ressources des acteurs impliqués.',
    definitionNgiem: 'Nzẅìŋ meshÿó lɔg ńkẅiʼi legye né shúmó fàʼ pʉ̀a pie pɔ́ gẅiin nò na lesẅɛ̀ menɔ̀ɔn',
    sourceFr: 'Plan stratégique PPA – IV.4.3.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)- Kèm IV.4.3.3',
    synonymesFr: 'Développement des compétences', synonymesNgiem: 'Lekẅìʼi legye pʉ̀a na nò lesẅɛ̀ mekúnɔ̀ɔn',
    contexteFr: 'Appliqué aux laboratoires, relais communautaires et éleveurs pour mieux lutter contre la PPA.', contexteNgiem: 'Yɔɔn zsénò kẅéte pafaʼa tsɛ̀ɛ mendá mashʉ́ŋ lɔ́gtà, ńgÿo pʉ̀a pie pɔ́ gẅiin légʉa tsɛ̀ɛ meláʼ, ńgab ntÿɔgɔ́ nâ pasẅɛ̀ menɔ̀ɔn, lélɔg ńdÿɔ́ʼɔ Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)',
    idFiche: 'ISTICMEM25CAROLDFT9', imageUrl: 'https://images.unsplash.com/photo-1542601906-990-b4d3fb778b09?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '10', termeFr: 'Peste Porcine Africaine (n.f)', termeNgiem: 'Gwáʼa Mekúnɔ̀ɔn Afílikà', domaineFr: 'Médecine vétérinaire', domaineNgiem: 'Lɔ́gtà lezòŋ menɔ̀ɔn',
    sousDomaineFr: 'Pathologie porcine', sousDomaineNgiem: 'Guɔ mekúnɔ̀ɔn',
    definitionFr: 'Une maladie virale hautement infectieuse touchant les porcs domestiques ainsi que les suidés sauvages.',
    definitionNgiem: 'Tsɔ́ guɔ gie vilẅîs zɔ nǎ, á piŋ ńgwoon mekúnɔ̀ɔn nâ tsɔ́ menɔ̀ɔn mbàʼ mie é sẅé wɔ́b tɛʼ.',
    sourceFr: 'Plan opérationnel PPA – I.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)- Kèm I.3',
    synonymesFr: 'Fièvre porcine africaine, maladie de Montgomery', synonymesNgiem: 'Nnɛ́ Mekúnɔ̀ɔn Afílikà, Guɔ Moŋgɔmelî',
    contexteFr: 'Évolue sur un mode épizootique rapidement mortel ; signalée au Cameroun depuis 1982.', contexteNgiem: 'Á gáʼa na ntí ye guɔ menɔ̀ɔn pɔ́ letʉ́ tà ńcʉ́me pɔ́ ne legwé ; Mé la láʼte guɔ mɛ́ Kamalûm tà fó na nguʼ 1982',
    idFiche: 'ISTICMEM25CAROLDFT10', imageUrl: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '11', termeFr: 'Porcs domestiques (n.m)', termeNgiem: 'Mekúnɔ̀ɔn mbʉ̀a', domaineFr: 'Élevage', domaineNgiem: 'Lesẅɛ̀ menɔ̀ɔn',
    sousDomaineFr: 'Espèce cible', sousDomaineNgiem: 'Ntí nɔ̀ɔn gie guɔ nɔ́ɔnte',
    definitionFr: "Animal domestiqué par l'homme, il est la principale victime de la PPA",
    definitionNgiem: 'Aa nɔ̀ɔn gẅie nyìŋ mesoŋ pfelé, á piŋ ńgwɔ́ mvɔ̀g mvfò na pie é kaa Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA)',
    sourceFr: 'Plan opérationnel PPA – I.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) – I.3',
    synonymesFr: 'Cochon', synonymesNgiem: 'Kúnɔ̀ɔn',
    contexteFr: 'La PPA affecte principalement les porcs domestiques dans les zones d’élevage.', contexteNgiem: 'Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) lwa ńgwoon pɔ́ mekúnɔ̀ɔn mbʉ̀a na jʉʼ sie mé sẅɛɛ wɔ́b wó',
    idFiche: 'ISTICMEM25CAROLDFT11', imageUrl: 'https://images.unsplash.com/photo-1544333323-c242144ebd53?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '12', termeFr: 'Suidés sauvages (n.m)', termeNgiem: 'Mekúnɔɔn mbàʼ', domaineFr: 'Faune sauvage', domaineNgiem: 'Menɔ̀ɔn mbàʼ',
    sousDomaineFr: 'Espèce réservoir', sousDomaineNgiem: 'Ntí menɔ̀ɔn pie é gẅiin mmó gie á náa guɔ té gwe guɔ',
    definitionFr: 'Espèces porcines non domestiquées pouvant être porteuses asymptomatiques du virus de la PPA',
    definitionNgiem: 'Ntí mekúnɔ̀ɔn pe mbàʼ pie ńgwɔ́ pɔ́ gẅiin vilẅîs Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) té gwe guɔ ya yɛ̌.',
    sourceFr: 'Plan opérationnel PPA – I.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm – I.3',
    synonymesFr: 'Phacochères, sangliers', synonymesNgiem: 'Mekúnɔ̀ɔn tsẅɛ',
    contexteFr: 'Peuvent transmettre la maladie sans présenter de symptômes.', contexteNgiem: 'Ńgwɔ́ pɔ́ maʼa guɔ na tsɔ́ menɔ̀ɔn té gwɔ́ gie kwàʼ pɔ́b mɛ́ ŋwɛ́ gwě guɔ',
    idFiche: 'ISTICMEM25CAROLDFT12', imageUrl: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '13', termeFr: 'Symptômes nerveux (n.m)', termeNgiem: 'lejǔʼ kékáŋ na púɔ menŋaŋ nnɛ́', domaineFr: 'Médecine vétérinaire', domaineNgiem: 'Lɔ́gtà lezòŋ menɔ̀ɔn',
    sousDomaineFr: 'Sémiologie porcine', sousDomaineNgiem: 'Lezsé meliŋé meguɔ mekúnɔ̀ɔn',
    definitionFr: 'Manifestations cliniques affectant le système nerveux, telles que tremblements, convulsions ou désorientation',
    definitionNgiem: 'Mefǔɔ guɔ mie é kíbe púɔ menŋaŋ nnɛ́ nɔ̀ɔn páʼ levɛ̀, letìŋ, lepyě legye',
    sourceFr: 'Plan opérationnel PPA – I.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm – I.3',
    synonymesFr: 'Troubles neurologiques', synonymesNgiem: 'Lepyě legye',
    contexteFr: 'Peuvent apparaître dans les formes graves de PPA, notamment en phase terminale.', contexteNgiem: 'Mɔɔn meliŋé sáʼ fʉ̀ʼ gie Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) pǔ ńdẅɛ tà ńcʉʼʉ faʼa pɔ́ lézẅé nɔ̀ɔn',
    idFiche: 'ISTICMEM25CAROLDFT13', imageUrl: 'https://images.unsplash.com/photo-1574313180911-376092790906?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '14', termeFr: 'Lésion hémorragique (n.f)', termeNgiem: 'mekenkÿo metse lézaʼte', domaineFr: 'Médecine vétérinaire', domaineNgiem: 'Lɔ́gtà lezòŋ meguɔ',
    sousDomaineFr: 'Pathologie porcine', sousDomaineNgiem: 'Guɔ mekúnɔ̀ɔn',
    definitionFr: "Altérations des tissus caractérisées par des saignements internes observables lors de l'autopsie",
    definitionNgiem: 'Megígyé jʉʼʉ nnɛ́ lécʉŋte, efʉ̀ʼ gwɔ́ páʼ mé kɔ́ʼɔ kúnɔ̀ɔn, ńgyɛ́ metse na shúm lepfòm sé',
    sourceFr: 'Plan opérationnel PPA – I.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm – I.3',
    synonymesFr: 'Saignements internes', synonymesNgiem: 'Metse lékẅɛ na shúm lepfòm',
    contexteFr: 'Dans les cas récents de PPA, elles sont discrètes et localisées aux reins et ganglions gastro-intestinaux.', contexteNgiem: 'Á gʉa na menɔ̀ɔn pie é ka giŋé ńgẅiin Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA), mekenkÿo metse lézaʼte náʼa ńgwɔ́ pɔ́ lélyěen, páʼ tsɛ̀ɛ mbàŋ nkàʼ kà tsɛ̀ɛ metú wɔ́ɔ.',
    idFiche: 'ISTICMEM25CAROLDFT14', imageUrl: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '15', termeFr: 'Symptômes digestifs (n.m)', termeNgiem: 'Lejǔʼ kékáŋ tsɛ̀ɛ lepfòm', domaineFr: 'Médecine vétérinaire', domaineNgiem: 'Lɔ́gtà lezòŋ menɔ̀ɔn',
    sousDomaineFr: 'Sémiologie porcine', sousDomaineNgiem: 'Lezsé meliŋé meguɔ mekúnɔ̀ɔn',
    definitionFr: "Manifestations cliniques touchant le système gastro-intestinal, comme la diarrhée, les vomissements ou l'inappétence.",
    definitionNgiem: 'Mefǔɔ guɔ mie é kíbe majÿó nâ metú kúnɔ̀ɔn, ńzéʼe, ncwò wé té pòŋ.',
    sourceFr: 'Plan opérationnel PPA – I.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm – I.3',
    synonymesFr: 'Troubles digestifs', synonymesNgiem: 'Lejǔʼ tepòŋ tsɛ̀ɛ lepfòm',
    contexteFr: 'Observés chez les porcs atteints de PPA, souvent associés à un retard de croissance.', contexteNgiem: 'Mé gyɛ́ wɔɔn legwɔ́ na mekúnɔ̀ɔn pie pɔ́ gẅiin Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA), ńtʉʉ lélÿo, pɔ́ tuʼ.',
    idFiche: 'ISTICMEM25CAROLDFT15', imageUrl: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '16', termeFr: 'Zone infectée', termeNgiem: 'Jʉʼ gie guɔ áa wó', domaineFr: 'Épidémiologie', domaineNgiem: 'Zsénò na nò meguɔ tsɛ̀ɛ láʼ',
    sousDomaineFr: 'Cartographie sanitaire', sousDomaineNgiem: 'Ntí gie guɔ áa púʼu tsɛ̀ɛ tàʼa láʼ',
    definitionFr: 'Aire géographique où la PPA est confirmée, soumise à des mesures strictes de lutte.',
    definitionNgiem: 'Pàga láʼ gie Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) áa wó, mbà mé pǐŋ ńkaa tsɔ́ nzẅìŋ mefàʼ lélɔg ḿbyága yé.',
    sourceFr: 'Plan stratégique PPA –IV.4.4.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm –IV.4.4.3',
    synonymesFr: 'Zone foyer', synonymesNgiem: 'Letsiŋé/ Lekye mmɔ̌g',
    contexteFr: 'Délimitée sur un rayon de 5 à 50 km autour du foyer confirmed.', contexteNgiem: 'Á záʼte na páʼ lefǒ soŋ, ńkúu na ngʉ̀ŋe, ńgwɔ́ léfó na mekílòmítà 5 ńkúu na 50',
    idFiche: 'ISTICMEM25CAROLDFT16', imageUrl: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '17', termeFr: 'Zone de surveillance (n.f)', termeNgiem: 'Jʉʼ gie mé ne ńdíe kà guɔ saʼá wó wɔ́ɔ', domaineFr: 'Épidémiologie', domaineNgiem: 'Zsénò na nò meguɔ tsɛɛ láʼ',
    sousDomaineFr: 'Cartographie sanitaire', sousDomaineNgiem: 'Ntí gie guɔ áa púʼu tsɛɛ tàʼa láʼ',
    definitionFr: 'Périmètre entourant la zone infectée, soumis à une vigilance renforcée.',
    definitionNgiem: 'Nkenkèle jʉʼ gie guɔ áa wó, á gie mé ne fɔ́gɔ nÿɔ́g mǒ mboŋó.',
    sourceFr: 'Plan stratégique PPA – IV.4.4.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm –IV.4.4.3',
    synonymesFr: 'Zone tampon', synonymesNgiem: 'Jʉʼ gie á tyé tsetsɛ̀ɛ gie guɔ áa wó pɔ́ gie á té wó wɔ́ɔ',
    contexteFr: 'S’étend sur un rayon de 25 km autour de la zone infectée.', contexteNgiem: 'Á záʼte na páʼ lefǒ lepàa jʉʼ gie guɔ áa wó ńkúu na ngʉ̀ŋe wé, ńgwɔ́ mekílòmítà 25.',
    idFiche: 'ISTICMEM25CAROLDFT17', imageUrl: 'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '18', termeFr: 'Zone de sécurité (n.f)', termeNgiem: 'Jʉʼ gie guɔ té wó wɔ́ɔ', domaineFr: 'Épidémiologie', domaineNgiem: 'Zsénò na nò meguɔ tsɛ̀ɛ láʼ',
    sousDomaineFr: 'Prévention', sousDomaineNgiem: 'Lepɔ̌ɔn guɔ',
    definitionFr: 'Périmètre externe visant à prévenir l’introduction du virus dans les zones indemnes.',
    definitionNgiem: 'Nkènkele jʉʼ gie ee nzème pǐ, é gie e kẅéte lélɔg ḿbɔ́ɔn guɔ lézyɛ́ʼ ńkúu tsɛ̀ɛ gie á té wó wɔ́ɔ.',
    sourceFr: 'Plan stratégique PPA – IV.4.4.3', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm –IV.4.4.3',
    synonymesFr: 'Zone indemne', synonymesNgiem: 'Jʉʼ gie guɔ té wó wɔ́ɔ',
    contexteFr: 'Surveillance hebdomadaire des élevages et contrôle des mouvements.', contexteNgiem: 'Lefɔ̌g nÿɔ́g ngàb ntsèm na mekab, ḿbiŋ ńdíe ntí gie mekúnɔ̀ɔn ne ńkẅɛɛ, ńkúu.',
    idFiche: 'ISTICMEM25CAROLDFT18', imageUrl: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
  {
    id: '19', termeFr: 'Alerte précoce (n.f)', termeNgiem: 'Legÿo mé zsé tà guɔ gíne ńzyete zyéte', domaineFr: 'Veille sanitaire', domaineNgiem: 'Lepyɛ̌b jʉʼ ńtíi guɔ',
    sousDomaineFr: 'Communication d’urgence', sousDomaineNgiem: 'Letsẅi menkʉ̀ pɔ́ ntsó tsǒ/ pɔ́ le metʉ̀',
    definitionFr: 'Transmission rapide d’une suspicion de foyer aux autorités compétentes pour déclencher une response immédiate.',
    definitionNgiem: 'Letsẅi nkʉ̀ mbwó ngúmnɔ̀ɔn, páʼ mé gyeté ngie tsɔ́ letsiŋé guɔ kẅɛ̌ɛ, ńdɔg ńtsɔ́ɔn páʼ pɔ́ ge lwa tsɔ́ʼɔ piŋé',
    sourceFr: 'Plan stratégique PPA – IV.4.4.1', sourceNgiem: 'Letáŋte lélÿɔʼ ncù na nò Gwáʼa Mekúnɔ̀ɔn Afílikà (PPA) Kèm –IV.4.4.1',
    synonymesFr: 'Notification rapide', synonymesNgiem: 'Leshwǒŋ té zẅíʼte',
    contexteFr: 'Permet de réduire le risque de propagation de la maladie.', contexteNgiem: 'Á kẅéte létsẅɛ́te nzẅìŋ gẅie ńgwɔ́ guɔ lɔg saa láʼ',
    idFiche: 'ISTICMEM25CAROLDFT19', imageUrl: 'https://images.unsplash.com/photo-1519003722824-192d99a38f0c?q=80&w=800&auto=format&fit=crop',
    auteur: 'Carol Douanla', dateCreation: '2025-01-20', statut: 'valide'
  },
];

export const LESSONS: Lesson[] = [
  { id: 'l1', title: 'Fondamentaux PPA', description: 'Comprendre le virus en Ngiembɔɔn.', icon: '📜', points: 100, completed: false, villageName: 'Marché Central' },
  { id: 'l2', title: 'Rites Sanitaires', description: 'Traditions et biosécurité.', icon: '🛖', points: 150, completed: false, villageName: 'Chefferie' },
  { id: 'l3', title: 'Signature SIG', description: 'Maîtriser les 19 fiches.', icon: '📑', points: 200, completed: false, villageName: 'Zone Sécurisée' },
  { id: 'l4', title: 'Verbes de Soin', description: 'Apprendre les verbes vétérinaires.', icon: '💉', points: 120, completed: false, villageName: 'Clinique Locale' },
  { id: 'l5', title: 'Dialogue Expert', description: 'Converser avec les notables.', icon: '💬', points: 180, completed: false, villageName: 'Conseil Supérieur' },
];

export const LEXIQUE_DATA = [
  { fr: 'Affichage public', ng: 'Lekìm menkʉ̀ na làŋa' },
  { fr: 'Autopsie', ng: 'Lekɔʼɔ́ pfó kúnɔ̀ɔn' },
  { fr: 'Avortement', ng: 'Letsege múɔ' },
  { fr: 'Biosécurité', ng: 'Meshÿó lɔg ńtáte guɔ légwoon menɔ̀ɔn' },
  { fr: 'Canal de communication', ng: 'Meshÿó lɔg ńtsẅi menkʉ̀' },
  { fr: 'Contrôle de l’application', ng: 'Legyɛ̌ páʼ shúm ne ńgiŋe' },
  { fr: 'Diagnostic virologique', ng: 'Lefaʼa vilẅîs na nɔ̀ɔn gẅie à ne ńguɔ' },
  { fr: 'Contagieuse', ng: 'Guɔ léfó na kúnɔ̀ɔn ńkúu na tsɔ̌' },
  { fr: 'Contamination', ng: 'Guɔ légwoon kúnɔ̀ɔn' },
  { fr: 'Éleveur porcin', ng: 'Sẅɛ̀ mekúnɔ̀ɔn' },
  { fr: 'Épidémie', ng: 'Guɔ gie á léen léen' },
  { fr: 'Épizootie', ng: 'Guɔ menɔ̀ɔn gie á léen léen' },
  { fr: 'Fièvre', ng: 'Nnɛ́' },
  { fr: 'Formation des acteurs', ng: 'Letsyèen pʉ̀a pie pɔ́ gẅiin nò na lesẅɛ̀ mekúnɔ̀ɔn' },
  { fr: 'Formation de formateurs', ng: 'Letsyèen patsyèen pʉ̀a' },
  { fr: 'Ganglions gastro-intestinaux', ng: 'Púɔ mevòm shúm sie ée tsɛ̀ɛ majÿó nâ metú nɔ̀ɔn' },
  { fr: 'Inappétence', ng: 'Ncwò nɔ̀ɔn lepÿág' },
  { fr: 'Isolement', ng: 'Lekíŋ' },
  { fr: 'Langue locale', ng: 'Shwóŋè láʼ' },
  { fr: 'Lésions hémorragiques', ng: 'Mekenkÿo metse lézaʼte' },
  { fr: 'Maladie virale', ng: 'Guɔ gie vilẅîs zɔ nǎ' },
  { fr: 'Marché porcin', ng: 'Sɔ̌ɔn mekúnɔ̀ɔn' },
  { fr: 'Matériel d’élevage', ng: 'Shúm lɔg sẅɛ menɔ̀ɔn' },
  { fr: 'Médias communautaires', ng: 'Shúm lɔg ńtsege menkʉ̀ tsɛ̀ɛ láʼ' },
  { fr: 'Message de sensibilisation', ng: 'Nkʉ̀ lɔg ńcwoŋo shwóŋ pʉ̀a' },
  { fr: 'Porcs domestiques', ng: 'Mekúnɔ̀ɔn mbʉ̀a' },
  { fr: 'Porteur sain', ng: 'Nɔ̀ɔn gẅie à gẅiin mmó gie á náa guɔ tá ńké te gwe guɔ wɔ́' },
  { fr: 'Prélèvement biologique', ng: 'Lesɔbɔ jʉʼʉ nnɛ́ nɔ̀ɔn kà metse mé wɔ́ɔ, Létsáase' },
  { fr: 'Prévention', ng: 'Lepɔ̌ɔn guɔ' },
  { fr: 'Propagation', ng: 'Lesà jʉʼ' },
  { fr: 'Rapportage de cas', ng: 'Legÿo tà ngúmnɔ̀ɔn zsé. Menɔ̀on pie é ne ńguɔ' },
  { fr: 'Reins', ng: 'Mbaŋ nkàʼ' },
  { fr: 'Relais communautaire', ng: 'Pʉ̀a pie é gẅiin légʉa tsɛ̀ɛ láʼ, ńgab ntÿɔgɔ́' },
  { fr: 'Règles de biosécurité', ng: 'Lesẅɛ̀ menɔ̀ɔn na nti gie ńgwɔ́ guɔ le wɔ́b gwoon' },
  { fr: 'Retard de croissance', ng: 'Letùʼ' },
  { fr: 'Septicémie', ng: 'Mbùm nnɛ́ légíɛ ngɔ́ʼ tɛʼ ńcʉa na tsɔ̌ ntʉ̀ pa guɔ' },
  { fr: 'Suivi communautaire', ng: 'Lelíe páʼ kɔ́ɔkɔ́ɔ ne ńcʉate tsɛ̀ɛ láʼ ńtíi guɔ' },
  { fr: 'Suidés sauvages', ng: 'Mekúnɔɔn mbàʼ' },
  { fr: 'Symptômes digestifs', ng: 'Meliŋé guɔ tsɛ̀ɛ lepfòm' },
  { fr: 'Symptômes nerveux', ng: 'Meliŋé guɔ na púɔ menŋaŋ nnɛ́' },
  { fr: 'Symptômes respiratoires', ng: 'Lezẅìge kékáŋ' },
  { fr: 'Transmission communautaire', ng: 'Letsège menkʉ̀ tsɛ̀ɛ láʼ' },
  { fr: 'Transport d’animaux', ng: 'Lekàa menɔ̀ɔn' },
  { fr: 'Vulgarisation', ng: 'Legÿo pʉ̀a tà ńgyɔ́ɔn júʼ menkʉ̀ ńtíi guɔ' },
  { fr: 'Vulgarisation des règles', ng: 'Legÿo pʉ̀a tà ńgyɔ́ɔn júʼ mbʉ̌ ńtíi guɔ' },
  { fr: 'Zone infectée', ng: 'Jʉʼ gie guɔ áa wó' },
  { fr: 'Zone de sécurité', ng: 'Jʉʼ gie guɔ té wó wɔ́ɔ' },
];

export const GLOSSAIRE_DATA = [
  { id: 1, fr: 'Biosécurité', def: 'Ensemble de mesures pour empêcher l’entrée ou la propagation de la maladie', ng: 'Meshÿó lɔg ńtáte guɔ légwoon menɔ̀ɔn' },
  { id: 2, fr: 'Canal de communication', def: 'Moyen utilisé pour transmettre un message (radio, affiche, etc.)', ng: 'Meshÿó lɔg ńtsẅi menkʉ̀' },
  { id: 3, fr: 'Diagnostic virologique', def: 'Test en laboratoire pour détecter le virus', ng: 'Lefaʼa vilẅîs na nɔ̀ɔn gẅie à ne ńguɔ' },
  { id: 4, fr: 'Formation des acteurs', def: 'Apprentissage pour mieux prévenir et détecter la maladie', ng: 'Létsyeen pasẅɛ̀ mekúnɔ̀ɔn' },
  { id: 5, fr: 'Lésions hémorragiques', def: 'Saignements internes visibles à l’autopsie', ng: 'mekenkÿo metse lézaʼte' },
  { id: 6, fr: 'Médias communautaires', def: 'Radios ou journaux locaux utilisés pour informer', ng: 'Shúm lɔg ńtsege menkʉ̀ tsɛ̀ɛ láʼ' },
  { id: 7, fr: 'Message de sensibilisation', def: 'Contenu qui informe ou alerte sur la maladie', ng: 'Nkʉ lɔg ńcwoŋo shwóŋ pʉ̀a' },
  { id: 8, fr: 'Peste Porcine Africaine', def: 'Maladie virale très contagieuse et souvent mortelle chez les porcs', ng: 'Gwáʼa Mekúnɔ̀ɔn Afílikà' },
  { id: 9, fr: 'Porcs domestiques', def: 'Espèce animale élevée par l’homme, principale victime de la PPA.', ng: 'Mekúnɔ̀ɔn mbʉ̀a' },
  { id: 10, fr: 'Porteur sain', def: 'Individu ou animal infecté par un agent pathogène sans présenter de symptômes cliniques.', ng: 'Nɔ̀ɔn gẅie à gẅiin mmó gie á náa guɔ tá ńké te gwe guɔ wɔ́' },
  { id: 11, fr: 'Prélèvement biologique', def: 'Action de recueillir des échantillons biologiques (sang, organes, tissus) pour analyse en laboratoire.', ng: 'Lesɔbɔ jʉʼʉ nnɛ́ nɔ̀ɔn kà metse mé wɔ́ɔ, létsáase' },
  { id: 12, fr: 'Rapportage de cas', def: 'Signalement d’un cas suspect ou confirmé', ng: 'Legÿo tà ngúmnɔ̀ɔn zsé. Menɔ̀on pie é ne ńguɔ' },
  { id: 13, fr: 'Abattage sanitaire', def: '(Personne formée localement pour transmettre les messages de prévention)', ng: 'Lezẅeté menɔ̀ɔn ńtíi guɔ' },
  { id: 14, fr: 'Règles de biosécurité', def: 'Consignes à suivre pour éviter la maladie', ng: 'Meshÿó lɔg ńtáte guɔ légwoon menɔ̀ɔn' },
  { id: 15, fr: 'Septicémie', def: 'Infection généralisée du sang causée par la présence de bactéries ou de virus, entraînant une réaction inflammatoire grave.', ng: 'Metse lepÿág ńtí mevilẅîs' },
  { id: 16, fr: 'Suidés sauvages', def: 'Espèces porcines non domestiquées pouvant être porteuses saines du virus de la PPA', ng: 'Mekúnɔɔn mbàʼ' },
  { id: 17, fr: 'Suivi communautaire', def: 'Vérification locale de l’application des règles', ng: 'Lelíe páʼ kɔ́ɔkɔ́ɔ ne ńcʉate tsɛ̀ɛ láʼ ńtíi guɔ' },
  { id: 18, fr: 'Relai communautaire', def: 'Approche impliquant activement les communautés dans la détection, le signalement et la prévention des maladies animales.', ng: 'Nyìŋ gẅie à gẅiin légʉa tsɛ̀ɛ láʼ, ńgab ntÿɔgɔ́' },
  { id: 19, fr: 'Symptômes digestifs', def: 'Signes comme la diarrhée, l’inappétence', ng: 'Lejǔʼ kékáŋ tsɛ̀ɛ lepfòm' },
  { id: 20, fr: 'Vulgarisation', def: 'Action de rendre les informations techniques faciles à comprendre', ng: 'Legÿo pʉ̀a tà ńgyɔ́ɔn júʼ menkʉ̀ ńtíi guɔ' },
];
